### ISSUE TITLE
Support not SemVer versions

### ISSUE THREAD

**Issue by juherr** [zafarkhaja/jsemver#15]
Sadly, everyone doesn't use SemVer but it could be useful to use jsemver in order to compare versions in the SemVer way.
In this case, a `boolean isSemVer()` method could be usefull.

**Comment by mwanji** [comment]
A partial non-SemVer support that would be really handy would be a String equivalent to Version.forIntegers (which could be rolled into Version.valueOf, I guess). It would accept "partial" versions, such as "1" and "1.0". Since this functionality exists for ints, it would be nice to have it for Strings, too.

**Comment by zafarkhaja** [comment]
@mwanji there is a subtle difference between `Version.forIntegers()` and `Version.valueOf()`. The former, one with 3 formal parameters (major, minor, patch), is an optimized version of the latter, that is if you need a simple version, say `1.0.0`, you don't have to go through the whole parsing process. It's been overridden to have fewer parameters for the sake of convenience which, as it turns out, might not have been a good idea. The string passed to `Version.valueOf()`, on the other hand, undergoes the formal parsing process which has to abide to the formal grammar which doesn't allow optional major and patch versions. I've opened a [discussion](https://github.com/mojombo/semver/issues/237) for this but so far the community seems to dislike the idea.

**Comment by mwanji** [comment]
I understand the resistance, but as you mention in the other issue, partial versions are allowed in comparisons.

This behaviour doesn't have to be in valueOf, but not having it at all forces clients to do some parsing of their own, for rather trivial reasons. In my case, I was parsing browser data from caniuse.com, and going from a version string that may or may not have 3 parts to one that does is fairly annoying.

**Comment by RobertFischer** [comment]
+1 for allowing partial versions in String parsers. I'm having to special-case those for parsing out REST API versions, which the users want to specify as the string, "2".

**Comment by zafarkhaja** [comment]
I'll be providing the support for partial versions with the next release (`0.10.0`).

**Comment by zafarkhaja** [comment]
As of 0.10.0 it will be possible to parse shorter versions, but not longer ones. Hopefully the next release will support this.
