### ISSUE TITLE
Metod parameter is not being used.

### ISSUE THREAD

**Issue by Kubuxu** [zafarkhaja/jsemver#20]
This method does not use `input` parameter: https://github.com/zafarkhaja/jsemver/blob/master/src/main/java/com/github/zafarkhaja/semver/VersionParser.java#L180

**Comment by zafarkhaja** [comment]
Hi @Kubuxu, thank you for the report.

I know it's not used, it's there just for the sake of [Parser.parse(String input)](https://github.com/zafarkhaja/jsemver/blob/master/src/main/java/com/github/zafarkhaja/semver/Parser.java#L42) signature compatibility to correctly implement the method. It felt right in the beginning to have a functional interface for the parser which is also implemented by [ExpressionParser](https://github.com/zafarkhaja/jsemver/blob/master/src/main/java/com/github/zafarkhaja/semver/expr/ExpressionParser.java). However, due to some previous design decisions, I failed to implement the `VersionParser` as a pure function, so it remains like that. At least for now.

**Comment by Kubuxu** [comment]
Oh. Would be it possible to annotate that in JavaDoc of this function in `VersionParser`. I was a little bit confused while reading that.

**Comment by zafarkhaja** [comment]
Sorry for the delay. Of course, I'll do so as soon as possible unless you want to submit a pull request.
