### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by decebals** [zafarkhaja/jsemver#56]
@zafarkhaja 
First of all, many thanks for this library. It's really useful.
We have in [PF4J](https://github.com/pf4j) an open issue https://github.com/pf4j/pf4j/issues/303 related to your library.
I would ask you to express your opinion about the future of your project. We want to know if you continue to maintain this project or not.
They are some [forks](https://github.com/zafarkhaja/jsemver/network) they are more or less active maintained but I think that is better for the future of this project to have all the modifications (bug fixing, new features) in a single place.
If you don't have time, probably you can delegate other person as maintainer of this library.
I want the work you started on this project to continue in the future.
Looking forward to hearing from you

**Comment by cdancy** [comment]
@decebals wondering the same. Was going to open an ISSUE as well but doesn't look like the developer has been on github in years. Maybe best to fork?

**Comment by decebals** [comment]
@cdancy I see that @zafarkhaja has the email in the profile. In the end we will find a modality to contact him. We just want a simple answer. We should have little patience.
Honestly, I prefer to not fork it but if the answer is that the project is dead, a good solution I think is to create an organization with name `jsemver` (I see that `jsemver.org` is available) and to continue the work on this project. So I proceeded with [PF4J](https://github.com/pf4j) and [Pippo](https://github.com/pippo-java). 
But, again, I hope that Zafar to continue to maintain this project.

**Comment by PhantomYdn** [comment]
Recommend to check this fork: https://github.com/AntiLaby/jsemver by @AntiLaby team

**Comment by zafarkhaja** [comment]
Is it dead? I definitely hope not!

Hello everyone,

First of all, let me thank you guys and all the users of `jsemver` for your patience and support. @decebals special thanks to you for putting your faith in me ;)

As @cdancy correctly pointed out I haven't been here for a while, maintaining an OSS project wasn't a priority for me for quite a long time. To be honest, at some point I even lost interest in the library mainly because I wasn't "dogfooding" it and partly because I got stuck... And it also felt like the specification itself was stagnating too. But here I am again, eager to pick up where I left off and give it another shot. Seeing the recent activity on the specification front and the growing number of stars and users has only motivated me to make `jsemver` ~great again~ the best and most specification compliant SemVer library out there and I have all the intentions to do so.

So here's what I'm planning to do. First, I'm going to do some housekeeping and tweaking, will need to catch up with Github's new features. Then I'll make some long due small updates like updating the license years, upgrading dependencies, upgrading minimum required Java version to 8, completing community profile, etc. Further, I'll review the PRs and clean up the issues. After that I'm planning to bring the library up to date with the specification updates, if required. And then I guess we're back on track.

I don't want to give any estimates now, let's see how it goes. So, stay tuned and keep those issues coming :)

Yours truly, Zafar.

**Comment by decebals** [comment]
@zafarkhaja It's big pleasure to close this issue.

**Comment by PhantomYdn** [comment]
@zafarkhaja , sounds great!:) Please take a look to most productive fork: https://github.com/AntiLaby/jsemver by @AntiLaby. We in [JNPM](https://github.com/OrienteerBAP/JNPM) made dependency on this fork - so will be good to have all features merged back to roots;)

**Comment by cdancy** [comment]
> @zafarkhaja , sounds great!:) Please take a look to most productive fork: https://github.com/AntiLaby/jsemver by @AntiLaby. We in JNPM made dependency on this fork - so will be good to have all features merged back to roots;)

This should be done as first thing IMO and then build on top of that work as folks in the community have already started using that fork.

**Comment by zafarkhaja** [comment]
Wow, that was fast :)

@decebals I can only imagine

@PhantomYdn sure will do, thanks :+1:

**Comment by decebals** [comment]
@zafarkhaja Ping

**Comment by PhantomYdn** [comment]
@decebals , I recommend migrating to the following library:  https://github.com/vdurmont/semver4j
We did that in the following our commit: https://github.com/OrienteerBAP/JNPM/commit/1413aa430fa1208c9afd03f165dc3db700a41460 It's easy and not painful:)
Semver4j at least is alive.

**Comment by decebals** [comment]
@PhantomYdn Thanks for your recommendation. I will take a look on `semver4j` to see if it satisfies my need. To be honest I prefer an active fork of this project but in the end it's better than nothing :smile:. I hope that `semver4j` is maintained.
